os: osx
osx_image: xcode10
language: node_js
node_js: '10'
jobs:
  include:
    - stage: release
      if: tag IS present
      before_deploy:
      - HOMEBREW_NO_AUTO_UPDATE=1 brew install rpm
      - yarn dist
      deploy:
        provider: releases
        skip_cleanup: true
        api_key:
          secure: hic0RYf4foIapPgf/T6empN4SMHe+RORCwUO8abCU+8b4eVfssNcVm9MGDHXNLpmjuFW0d78DGQ55MfN6R9MPsMV7GIxGeKvYt+oWZcg7PlDFMYJyYGIOKRP/uQXz+wq0ndV4ub1o4lP/g6ti9j4XQqV3hbedbcZqVRgKQ/j4OLk23YiKwEyuZY6bdhnhqsEdU+oizantkaoqQwJyAaAQku++46cNxDvVIDKdv156j40O8Wc5ZyHoDHWiAGk5rlkIqqIKeyc7yELGzqt7wZXNayA2ysEcrLjCJuZ8j89Ku7KtYQwfE+KNE7vkWMI/LKGmVvhb/OQHGknvoNxTQIefVsl4M9fkpsN54ISyMBU/rcY63qrrLtLudlWJNmjFliE1b+932SzgZpCcm5ze9/MIEuOzxq4KjtgWW+kjOA3HahY2tTtYMrjjIYgbhhM8Ocp8GLsWJkC0q26vZ7/FVzY7O0Z9/CQIqqZ35vQHaK6NPvbbFY+gzXNC7e+XVB3BWNtpT+V8i9UbbTEm8+Rjs7WHXTS2dwLY259/g5nhnxZpUA+dvHg9pPnBWG4n+Y5GgsAKEexG8lNVVoLGzOYX9DJbEjDBIRUaLiPgizTNf6GCXiz7T5RdYom7U7ATXsg3b1PjlOZp8kxM1uz03QUO4jhJiZAaKyiZ5M8MIIMv3v8w+w=
        keep_history: true
        file_glob: true
        file: dist/*
        on:
          tags: true
